name: Run Pytests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  Build_install_and_test_forgd_core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.14

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Install forgd_core package
        run: |
          source venv/bin/activate
          pip install -e .

      - name: Run Pytest
        run: |
          source venv/bin/activate
          pytest -v -m "not integration"
